-- 커뮤니티

-- MEMBER
DROP TABLE MEMBER;
CREATE TABLE MEMBER (
    NO NUMBER
    , ID VARCHAR2(100)
    , PWD VARCHAR2(100)
    , NICK VARCHAR2(100)
    , ENROLL_DATE TIMESTAMP
    , QUIT_YN CHAR(1));

-- 회원가입
INSERT INTO MEMBER (NO, ID, PWD, NICK, ENROLL_DATE,QUIT_YN) VALUES (1, '아이디', 100000, '닉네임', SYSDATE,'N');
-- 로그인
SELECT * FROM MEMBER WHERE ID = '아이디' AND PWD = '비번';
-- 비번변경
UPDATE MEMBER SET PWD = '신규비번'
WHERE ID = '아이디' AND PWD = '비번';
-- 닉네임 변경
UPDATE MEMBER SET NICK = '신규닉네임'
WHERE ID = '아이디' AND PWD = '비번';
-- 탈퇴 --삭제 말고 QUIT_YN 칼럼은 Y 로 변경
UPDATE MEMBER
    SET QUIT_YN = 'Y'
    WHERE ID = '아이디'
    AND PWD = '비번';
-- 마이페이지 조회
SELECT *
FROM MEMBER
WHERE ID = '아이디' 
AND PWD = '비번'; 

-- BOARD
DROP TABLE BOARD;
CREATE TABLE BOARD (
    NO NUMBER
    , TITLE VARCHAR2 (100)
    , CONTENT VARCHAR2(4000)
    , WRITER_NO NUMBER
    , ENROLL_DATE TIMESTAMP
    , DEL_YN CHAR(1));
    
-- 게시글 작성
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO, ENROLL_DATE, DEL_YN) VALUES (1, '제목', '내용', 1, SYSDATE, 'Y');
-- 게시글 전체 목록 조회 (게시글제목, 작성일시, 작성자)
SELECT TITLE, ENROLL_DATE, WRITER_NO
FROM BOARD;
-- 게시글 상세조회
SELECT * 
FROM BOARD
WHERE NO = 1;
-- 게시글 제목 및 내용 수정
UPDATE BOARD SET TITLE = '새제목'
WHERE WRITER_NO = 777 AND TITLE = '제목';

UPDATE BOARD SET CONTENT = '새내용'
WHERE CONTENT = '내용' AND WRITER_NO = 777;
-- 게시글 삭제
DELETE BOARD 
WHERE TITLE = '제목' AND WRITER_NO = 777;
