-- QnA (cherry market)

/*CREATE TABLE "QNA" (
	"QNA_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MANAGER_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"MEMBER_ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NULL,
	"SECRET_YN"	CHAR(1)	DEFAULT 'Y'	NULL,
	"ANSWER"	VARCHAR2(4000)		NULL,
	"MANAGER_ENROLL_DATE"	TIMESTAMP	DEFAULT SYSDATE	NULL,
	"MANAGER_EDIT_DATE"	TIMESTAMP	DEFAULT SYSDATE	NULL
);
*/

--테이블 삭제
DROP TABLE QNA CASCADE CONSTRAINTS;

--시퀀스 생성
DROP SEQUENCE SEQ_QNA_NO;
CREATE SEQUENCE SEQ_QNA_NO NOCYCLE NOCACHE;

--테이블 생성
CREATE TABLE QNA (
    QNA_NO                  NUMBER              PRIMARY KEY         
    , MEMBER_NO             NUMBER             
    , MANAGER_NO            NUMBER              
    , TITLE                 VARCHAR2(1000)      NOT NULL
    , CONTENT               VARCHAR2(4000)      NOT NULL
    , MEMBER_ENROLL_DATE    TIMESTAMP           DEFAULT SYSDATE
    , SECRET_YN             CHAR(1)             DEFAULT 'Y' CHECK(SECRET_YN IN('Y', 'N'))
    , ANSWER                VARCHAR2(4000)
    , MANAGER_ENROLL_DATE   TIMESTAMP           DEFAULT SYSDATE
    , MANAGER_EDIT_DATE     TIMESTAMP           DEFAULT SYSDATE
);

COMMENT ON COLUMN "QNA"."QNA_NO" IS '게시글번호PK';
COMMENT ON COLUMN "QNA"."MEMBER_NO" IS '사용자번호FK';
COMMENT ON COLUMN "QNA"."MANAGER_NO" IS '관리자번호FK';
COMMENT ON COLUMN "QNA"."TITLE" IS '제목';
COMMENT ON COLUMN "QNA"."CONTENT" IS '내용';
COMMENT ON COLUMN "QNA"."MEMBER_ENROLL_DATE" IS '사용자의 게시글작성일';
COMMENT ON COLUMN "QNA"."SECRET_YN" IS '공개여부';
COMMENT ON COLUMN "QNA"."ANSWER" IS '관리자의 답변';
COMMENT ON COLUMN "QNA"."MANAGER_ENROLL_DATE" IS '관리자의 답변 작성일';
COMMENT ON COLUMN "QNA"."MANAGER_EDIT_DATE" IS '관리자 답변 수정 일자';

-- 외래키
ALTER TABLE QNA
ADD CONSTRAINT FK_QNA_MEMBER 
FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER (MEMBER_NO);

ALTER TABLE QNA
ADD CONSTRAINT FK_QNA_MANAGER 
FOREIGN KEY(MANAGER_NO) REFERENCES MANAGER (MANAGER_NO);


-- 더미 테이터(유저가 작성한 질문글)
INSERT INTO QNA(QNA_NO, MEMBER_NO, TITLE, CONTENT) VALUES(SEQ_QNA_NO.NEXTVAL, 5, '게시글 개수에 제한이 있나요?', '판매하고 싶은 제품이 많은데 게시글을 몇개 작성할 수 있는지 궁금합니다.');
INSERT INTO QNA(QNA_NO, MEMBER_NO, TITLE, CONTENT) VALUES(SEQ_QNA_NO.NEXTVAL, 3, '택배 거래도 가능한가요?', '판매자가 회사에 판매물품을 두고와서 직거래가 어렵다고 택배로 거래하자는데 가능할까요?');
INSERT INTO QNA(QNA_NO, MEMBER_NO, TITLE, CONTENT) VALUES(SEQ_QNA_NO.NEXTVAL, 7, '내 게시글이 안보여요.', '판매글을 작성했는데 게시글이 안보입니다.');
COMMIT;



-- 더미 테이터(관리자가 작성한 답글)
UPDATE QNA SET ANSWER = '하루에 20개의 게시글을 작성 할 수 있고, 한 사람당 300개의 게시글을 작성할 수 있습니다.' WHERE QNA_NO = 1;
UPDATE QNA SET ANSWER = '택배 거래는 가능합니다. 다만 택배거래는 항상 사기 위험이 있으니 유의하시길 바랍니다.' WHERE QNA_NO = 2;
UPDATE QNA SET ANSWER = '중복게시글을 작성하셨거나 전문판매없자 제재를 받은 경우 게시글이 안보일 수 있습니다.' WHERE QNA_NO = 3;
COMMIT;






