--mini

---------------------------------
--테이블 삭제
---------------------------------
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;

---------------------------------
--시퀀스 생성
---------------------------------
DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_BOARD_NO;

CREATE SEQUENCE SEQ_MEMBER_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_BOARD_NO NOCYCLE NOCACHE;

---------------------------------
--테이블 생성
---------------------------------

-- MEMBER
CREATE TABLE MEMBER(
    NO              NUMBER          PRIMARY KEY
    , ID            VARCHAR2(100)   NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , NICK          VARCHAR2(100)   NOT NULL UNIQUE
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE  TIMESTAMP
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N'))
);


-- BOARD
CREATE TABLE BOARD(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(100)   NOT NULL 
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , WRITER_NO     NUMBER          
    , HIT           NUMBER          DEFAULT 0
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE   TIMESTAMP
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N'))
);


---------------------------------
-- 외래키
---------------------------------
ALTER TABLE BOARD
ADD CONSTRAINT FK_BOARD_MEMBER 
FOREIGN KEY(WRITER_NO) REFERENCES MEMBER (NO);


---------------------------------
-- 더미 테이터
---------------------------------

--MEMBER
INSERT INTO MEMBER (NO, ID, PWD,NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'ADMIN', '1234', '관리자');
INSERT INTO MEMBER(NO, ID, PWD,NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'USER02', '1234', '닉네임02');
INSERT INTO MEMBER(NO, ID, PWD,NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'USER03', '1234', '닉네임03');
INSERT INTO MEMBER(NO, ID, PWD,NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'USER04', '1234', '닉네임04');
INSERT INTO MEMBER(NO, ID, PWD,NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'USER05', '1234', '닉네임05');
COMMIT;

--BOARD
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) VALUES(SEQ_BOARD_NO.NEXTVAL,'제목01', '내용01',3);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) VALUES(SEQ_BOARD_NO.NEXTVAL,'제목02', '내용02',4);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) VALUES(SEQ_BOARD_NO.NEXTVAL,'제목03', '내용03',5);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) VALUES(SEQ_BOARD_NO.NEXTVAL,'제목04', '내용04',2);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) VALUES(SEQ_BOARD_NO.NEXTVAL,'제목05', '내용05',2);
COMMIT;









