DROP TABLE MEMBER;


CREATE TABLE MEMBER(
    ID          VARCHAR2(100)
    , PWD       VARCHAR2(100)
    , NICK      VARCHAR2(100)
);

INSERT INTO MEMBER(ID, PWD, NICK) VALUES(?, ?, ?);

SELECT * FROM MEMBER;

CREATE TABLE BOARD (
    TITLE VARCHAR2(1000)
    , CONTENT VARCHAR2(4000)
);

INSERT INTO BOARD(TITLE, CONTENT) VALUES(?, ?);

SELECT * FROM BOARD;
